-- require "user.plugins"
-- require "user.tabline"
-- require "user.colorscheme"
-- require "user.cmp"
-- require "user.mason"
-- require "user.lspconfig"
-- require "user.comment"
-- require "user.gitsigns"
-- require "user.nvimtree"
-- require "user.indentblankline"
-- require "user.telescope"
-- require "user.whichkey"

require "core"
